### DISCUSSION TITLE
Importing GitHub Primer's css

### DISCUSSION THREAD

**Discussion by emwalker** [jaredpalmer/razzle#1619] [Q&A]
I'm trying to upgrade from Razzle 3.3.13 to Razzle 4.0.4 and Webpack 4 to Webpack 5, and there's an error that's occurring that I'm having trouble sorting out.  The error relates to an import of GitHub Primer CSS and is not raised in Razzle 3.3.13.

![2021-05-06_20-31](https://user-images.githubusercontent.com/760949/117389704-fea71180-aea9-11eb-87c7-794f2f1f5d4c.png)

If I squint my eyes, I suspect what's going on here is that my Razzle setup is not configured to handle the absolute path `/fonts/Inter-Regular.woff`, which is relative to `node_modules/@primer/css`.

There are several lines in different files where this may be happening:
```javascript
// src/client/index.tsx
import '@primer/css/index.scss?global'

// src/client/global.scss
@import '@primer/css/index.scss';
```

I've tried several modifications to the Webpack config in razzle.config.js, but none of them worked.  I'm not a big JS developer, so I'm not really sure what to do as a next step in troubleshooting this issue.  Any help is appreciated.

**Comment by squiddy** [comment]
All I can say for now is that I can easily reproduce the issue with

* starting a new razzle app (`npx create-razzle-app`)
* adding primer (`yarn add @primer/css`)
* adding the scss plugin (`yarn add razzle-plugin-scss` + razzle.config.js)

(Using webpack 4 though)

The SCSS plugin is using `resolve-url-loader` in it's loader chain, it deals with relative/absolute paths in CSS files, I'm looking into that now.

**Reply by squiddy** [reply]
https://github.com/primer/css/blob/v16.3.0/src/marketing/type/typography.scss#L6

```scss
@font-face {
  font-family: Inter;
  font-style: normal;
  font-weight: $font-weight-normal;
  src: local("Inter"), local("Inter-Regular"), url("#{$marketing-font-path}Inter-Regular.woff") format("woff");
  font-display: swap;
}
```

My guess is something in the webpack chain is trying to resolve the `url` part of that definition, that points by default to `/fonts/Inter-Regular.woff`.

**Update** The @primer/css package ships those fonts under `node_modules/@primer/css/fonts/Inter-Bold.woff`, so by adding that to the include paths for sass should work.
