### DISCUSSION TITLE
Google Cloud deployment

### DISCUSSION THREAD

**Discussion by andyzeli** [jaredpalmer/razzle#1785] [Q&A] [answered]
I am looking at deploying to GAE; curious why its not listed in the deployment options. anyone already do this? i think its just a matter of integrating GAEs app.yaml handler approach

**Comment by fivethreeo** [comment]
https://cloud.google.com/community/tutorials/run-expressjs-on-google-app-engine

https://cloud.google.com/appengine/docs/standard/nodejs/config/appref

https://cloud.google.com/appengine/docs/standard/nodejs/config/appref#handlers_element

does gcloud deploy upload files from static_dir entries in handlers?

**Comment by fivethreeo** [comment, marked as answer]
build with:

```shell
# .env.production
PUBLIC_PATH=/
```

```yml
# app.yml
runtime: nodejs
env: flex
entrypoint: build/server.js
handlers:
# All URLs beginning with /static are treated as paths to
# static files in the build/public/static directory.
- url: /static
  static_dir: build/public/static
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
```
