### ISSUE TITLE
Razzle deployment on k8s

### ISSUE THREAD

**Issue by vferdiansyah** [jaredpalmer/razzle#1215]
I'm trying to deploy a Razzle project into k8s cluster.
I can't seem to serve the static files since it uses port 3001 while ingress only exposes port 80 and 443. Can anyone point me in the right direction on how to solve this?

<img width="1653" alt="Screen Shot 2020-03-20 at 07 26 20" src="https://user-images.githubusercontent.com/12978330/77126585-3c659280-6a7c-11ea-872f-2ac4d0be4dba.png">

**Comment by fivethreeo** [comment]
If you deploy the production build you could just run on port 443. Why would you want to run dev deployed on a cluster?

**Comment by fivethreeo** [comment]
So just add

PORT=443
PUBLIC_URL=https://yoursite.com/

To
 .env.production

**Comment by vferdiansyah** [comment]
i'm not deploying production build. i'm still experimenting on my local cluster

**Comment by fivethreeo** [comment]
Well um, 80 without any ssl proxy in front.

**Comment by fivethreeo** [comment]
Ah, I use docker-compose for local dev. But no reason to run dev code unless you need to.

**Comment by fivethreeo** [comment]
Check out my razzle-with-docker-nginx for ways to do this and adapt it to k8s.

**Comment by fivethreeo** [comment]
Oh, you use docker-compose I see 😀

**Comment by vferdiansyah** [comment]
> Well um, 80 without any ssl proxy in front.

still not working :/

> Oh, you use docker-compose I see 😀

yeah i already use docker-compose in my local and it works just fine so i decided to take it a bit further by using local k8s cluster but it seems impossible to expose port 3001.

FYI, here is my ClusterIP, Ingress config, and deployment
```
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: client
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: <some_image>
          ports:
            - containerPort: 3000
```

**Comment by fivethreeo** [comment]
I’m no k8s expert but maybe

```yaml
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service-server
spec:
  type: ClusterIP
  selector:
    component: client
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service-devserver
spec:
  type: ClusterIP
  selector:
    component: client
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
             # PUBLIC_PATH
            backend:
              serviceName: client-cluster-ip-service-server
              servicePort: 3000          
         - path: /client/
            # CLIENT_PUBLIC_PATH
            backend:
              serviceName: client-cluster-ip-service-devserver
              servicePort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: <some_image>
          ports:
            - containerPort: 3000
            - containerPort: 3001
```

Also you need to use razzle-plugin-proxy. And maybe some more tweaking.

**Comment by jgcmarins** [comment]
This is how I've been running razzle on k8s on production:

## awesome-web-deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: awesome
  name: awesome-web
  labels:
    app: awesome-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: awesome-web
  template:
    metadata:
      labels:
        app: awesome-web
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: awesome-web
          image: 'us.gcr.io/awesome-123/awesome-web:latest'
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 20m
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
            periodSeconds: 30
          env:
            - name: PORT
              value: '8080'
          command:
            - node
            - server.js
---
apiVersion: v1
kind: Service
metadata:
  namespace: awesome
  name: awesome-web
  labels:
    app: awesome-web
spec:
  selector:
    app: awesome-web
  type: NodePort
  ports:
    - name: 'http'
      port: 80
      targetPort: 8080
      protocol: TCP

```

## ingress-nginx.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: awesome
  name: ingress-nginx
  labels:
    app: ingress-nginx
  annotations:
    kubernetes.io/ingress.global-static-ip-name: awesome-ip
spec:
  tls:
    - hosts:
        - awesome.dev
      secretName: awesome-tls
  rules:
    - host: awesome.dev
      http:
        paths:
          # /
          - path: /
            backend:
              serviceName: awesome-web
              servicePort: 80
          - path: /*
            backend:
              serviceName: awesome-web
              servicePort: 80
```
