### ISSUE TITLE
Missing dependencies when using Yarn 2 on razzle 3.x

### ISSUE THREAD

**Issue by icyrockcom** [jaredpalmer/razzle#1524]
### Current Behavior

This is from a fresh app created by:

```
$ yarn create razzle-app --no-install typescript-razzle-require-unsound
$ cd typescript-razzle-require-unsound
$ yarn set version berry
$ yarn install
$ yarn razzle start
```

A couple dependencies seem to be missing:

```
Error: @pmmmwh/react-refresh-webpack-plugin tried to access webpack, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Error: razzle tried to access postcss-load-config, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

These can be resolved by adding these in `.yarnrc.yml`:

```
packageExtensions:
  "@pmmmwh/react-refresh-webpack-plugin@*":
    peerDependencies:
      webpack: ^5.0.0
  razzle@*:
    dependencies:
      postcss-load-config: ^2.0.0
```

### Expected behavior

Should work out of the box.

### Reproducible example

https://github.com/icyrockcom/typescript-razzle-require-unsound

### Suggested solution(s)

Upgrading to this release might fix the first one https://github.com/pmmmwh/react-refresh-webpack-plugin/releases/tag/v0.4.3.

### Additional context

N/A.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.11
| Razzle Plugins   | None
| Node             | v14.15.4
| Browser          | N/A
| npm/Yarn         | Yarn 2.4.0
| Operating System | Linux (Xubuntu 20.04.1 LTS)
| TypeScript       | N/A
| React            | N/A
